# Generated by Django 5.0.6 on 2024-07-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_delete_about_delete_books_delete_gallery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Images/portfolio')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
