# Generated by Django 5.0.7 on 2024-07-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='Images/books')),
                ('spine', models.ImageField(upload_to='Images/books')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pages', models.IntegerField()),
                ('publication_date', models.DateField()),
                ('publisher', models.CharField(max_length=255)),
            ],
        ),
    ]
