# Generated by Django 5.0.7 on 2024-07-31 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
